### ISSUE TITLE
材料リストが取得できないケース

### ISSUE THREAD

**Issue by cloudliner** [terra-yucco/ruthenium#43]
## レシピ
[ほっこり〜栗の甘露煮](http://recipe.rakuten.co.jp/recipe/1570000075/)
### 表示結果
![screenshot 2016-10-12 22 40 42](https://cloud.githubusercontent.com/assets/594586/19312719/a8c3509c-90ce-11e6-9a85-1fa86d4781d4.png)

### レシピ画面
![screenshot 2016-10-12 22 42 24](https://cloud.githubusercontent.com/assets/594586/19312689/84c7a648-90ce-11e6-9010-8e1cfa2ad638.png)

### HTMLソース
```
<li itemprop="ingredients">
      <a href="/word/%E5%A1%A9/" sctag="recipe_basic_info_material_search" class="name" id="material_link">塩</a>
  <p class="amount">少々</p>
</li>
<li itemprop="ingredients">
      <div class="name">（あれば）クチナシの実</div>
  <p class="amount">1〜2個</p>
</li>
```

**Comment by cloudliner** [comment]
https://trello.com/c/bdxnqaGo

**Comment by terra-yucco** [comment]
まーじーでー…すか。
レシピ登録ページのフォーマット見てみよう。
